/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac-PC
 */
public class PanelRegistro extends javax.swing.JPanel {

    private VentanaPrincipal vp;

    /**
     * Creates new form PanelRegistrop
     */
    public PanelRegistro(VentanaPrincipal vp) {
        this.vp = vp;
        initComponents();
    }

    public void vaciarCampos() {
        jtfUsuario.setText("");
        jpfPass1.setText("");
        jpfPass2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpfPass1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jpfPass2 = new javax.swing.JPasswordField();
        jbRegistrado = new javax.swing.JButton();
        jcbShowPass = new javax.swing.JCheckBox();
        jcbShowPass2 = new javax.swing.JCheckBox();
        jbVolver = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Panel de Registro");

        jLabel2.setText("Introduzca Nombre usuario:");

        jLabel3.setText("Introduzca su contraseña(min 8 CHAR):");

        jpfPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPass1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Vuelva a introducir su contraseña:");

        jbRegistrado.setText("Crear");
        jbRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistradoActionPerformed(evt);
            }
        });

        jcbShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ShowPass.png"))); // NOI18N
        jcbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowPassActionPerformed(evt);
            }
        });

        jcbShowPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ShowPass.png"))); // NOI18N
        jcbShowPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowPass2ActionPerformed(evt);
            }
        });

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbVolver)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbRegistrado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jpfPass2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jpfPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbShowPass)
                            .addComponent(jcbShowPass2))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jpfPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jpfPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbShowPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbRegistrado)
                .addGap(30, 30, 30)
                .addComponent(jbVolver)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistradoActionPerformed
        // TODO add your handling code here:
        String pass1 = String.valueOf(jpfPass1.getPassword());
        String pass2 = String.valueOf(jpfPass2.getPassword());
        if (!jtfUsuario.getText().trim().isEmpty() && !pass1.isEmpty() && !pass2.isEmpty()) {
            if (vp.getConexion().getUsuario(jtfUsuario.getText().trim()) == null) {
                Usuario usuario = new Usuario();
                usuario.setUsuario(jtfUsuario.getText());
                if (pass1.compareTo(pass2) == 0) {
                    if (pass2.matches("(?=.*[0-9])(?=.*[A-z])(?=\\S+$).{8,}")) {
                        usuario.setPassword(pass2);
                        if (vp.getConexion().addUsuario(usuario)) {
                            JOptionPane.showMessageDialog(vp, "Usuario agregado correctamente.");
                            vp.login();
                            vaciarCampos();
                        } else {
                            JOptionPane.showMessageDialog(vp, "¡El usuario no se ha podido agregar!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(vp, "¡Minimo 8 caracteres,  numericos y letras!");
                    }
                } else {
                    JOptionPane.showMessageDialog(vp, "¡Las contraseñas no coinciden!");
                }
            } else {
                JOptionPane.showMessageDialog(vp, "¡El usuario ya existe!");
            }
        } else {
            JOptionPane.showMessageDialog(vp, "¡No pueden haber campos vacios!");
        }
    }//GEN-LAST:event_jbRegistradoActionPerformed

    private void jcbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowPassActionPerformed
        // TODO add your handling code here:
        if (jcbShowPass.isSelected()) {
            jpfPass1.setEchoChar((char) 0);
        } else {
            jpfPass1.setEchoChar('*');
        }
    }//GEN-LAST:event_jcbShowPassActionPerformed

    private void jcbShowPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowPass2ActionPerformed
        // TODO add your handling code here:
        if (jcbShowPass2.isSelected()) {
            jpfPass2.setEchoChar((char) 0);
        } else {
            jpfPass2.setEchoChar('*');
        }
    }//GEN-LAST:event_jcbShowPass2ActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        // TODO add your handling code here:
        vp.login();
        vaciarCampos();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jpfPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPass1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbRegistrado;
    private javax.swing.JButton jbVolver;
    private javax.swing.JCheckBox jcbShowPass;
    private javax.swing.JCheckBox jcbShowPass2;
    private javax.swing.JPasswordField jpfPass1;
    private javax.swing.JPasswordField jpfPass2;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
