/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Usuario;
import javax.swing.JOptionPane;
import oracle.jrockit.jfr.JFR;

/**
 *
 * @author Isaac-PC
 */
public class PanelMenu extends javax.swing.JPanel {

    private VentanaPrincipal vp;

    /**
     * Creates new form PanelMenu
     */
    public PanelMenu(VentanaPrincipal vp) {
        initComponents();
        this.vp = vp;
        jbAlta.setVisible(false);
        jbBaja.setVisible(false);
        jbListado.setVisible(false);
        jbModificacion.setVisible(false);
        jbCerrarSesion.setVisible(false);
    }

    public void habilitarComponentes() {
        jbAlta.setVisible(true);
        jbBaja.setVisible(true);
        jbListado.setVisible(true);
        jbModificacion.setVisible(true);
        jbCerrarSesion.setVisible(true);
    }

    public void deshabilitarComponentes() {
        jbAlta.setVisible(false);
        jbBaja.setVisible(false);
        jbListado.setVisible(false);
        jbModificacion.setVisible(false);
        jbCerrarSesion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAlta = new javax.swing.JButton();
        jbListado = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jbModificacion = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbCerrarSesion = new javax.swing.JButton();

        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbListado.setText("Listado");
        jbListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListadoActionPerformed(evt);
            }
        });

        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbModificacion.setText("Modificación");
        jbModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificacionActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbCerrarSesion.setText("Cerrar Sesion");
        jbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlta)
                    .addComponent(jbListado)
                    .addComponent(jbBaja)
                    .addComponent(jbModificacion)
                    .addComponent(jbSalir)
                    .addComponent(jbCerrarSesion)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListadoActionPerformed
        // TODO add your handling code here:
        vp.cambiaPanel(new PanelListado(vp));
    }//GEN-LAST:event_jbListadoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        vp.cerrarAplicaicon();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        vp.cambiaPanel(new PanelAlta(vp));
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        vp.cambiaPanel(new PanelBaja(vp));
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificacionActionPerformed
        // TODO add your handling code here:
        vp.cambiaPanel(new PanelModificacion(vp));
    }//GEN-LAST:event_jbModificacionActionPerformed

    private void jbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarSesionActionPerformed
        // TODO add your handling code here:
        vp.cambiaPanel(new PanelLogin(vp));
        vp.menu.deshabilitarComponentes();
    }//GEN-LAST:event_jbCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JButton jbListado;
    private javax.swing.JButton jbModificacion;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
