/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import persistencia.ConectaDB;

/**
 *
 * @author Isaac-PC
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    protected PanelMenu menu;
    private JPanel panelPrincipal;
    protected PanelAlta panelAlta;
    protected PanelLogin panelLogin;
    protected PanelRegistro panelRegistro;
    private ConectaDB conexion;

    /**
     * Creates new form VentanaPrinciapal
     */
    public VentanaPrincipal() {
        conexion = new ConectaDB();
        initComponents();
        distribuyeComponentes();
        this.setTitle("JDM Dealer");
    }

    protected void alta() {
        this.menu.habilitarComponentes();
        this.cambiaPanel(this.panelAlta);
    }

    protected void registrar() {
        this.cambiaPanel(this.panelRegistro);
    }

    protected void login() {
        this.cambiaPanel(this.panelLogin);
    }

    private void distribuyeComponentes() {
        menu = new PanelMenu(this);
        panelAlta = new PanelAlta(this);
        panelLogin = new PanelLogin(this);
        panelPrincipal = new JPanel();
        panelRegistro = new PanelRegistro(this);
        setLayout(new BorderLayout());
        add(menu, BorderLayout.NORTH);
        panelPrincipal.add(panelLogin);
        add(panelPrincipal, BorderLayout.CENTER);
    }

    public ConectaDB getConexion() {
        return conexion;
    }

    public void cambiaPanel(JPanel jp) {
        panelPrincipal.removeAll();
        panelPrincipal.add(jp);
        panelPrincipal.updateUI();
        panelPrincipal.repaint();
    }

    public void cerrarAplicaicon() {
        conexion.closeDB();
        System.exit(0);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/jdmIcon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
